### PR TITLE
Fix build error in mruby v1.2.0

### PR DESCRIPTION
**Pull request by hanachin**

### CODE REVIEW

**Comment by ksss** [comment]
@hanachin 
Seems good.
But I cann't represent build error on my OSX PC.

```sh
$ curl http://forum.mruby.org/download/source/mruby-1.2.0.tar.gz | tar xf -
$ cd mruby
$ # edit to add `conf.gem :mgem => "mruby-io-console"` to build_config.rb:24
$ make
$ ./build/host/bin/mirb
mirb - Embeddable Interactive Ruby Shell

> $stdout.noecho { $stdin.gets }
 => "aaa\n"
```

Could you explain in more detail?

**Comment by hanachin** [comment]
@ksss Thank you for take your time, I'll report more detail, Please give me a little more time.

**Comment by hanachin** [comment]
@ksss I created a reproduce code for this issue.
https://github.com/hanachin/build_error_example_for_mruby-io-console

First I got `mgem not found: mruby-error ` when build a mrbgem that depends to mruby-io-console.

```rb
# hi/mrbgem.rake
MRuby::Gem::Specification.new('hi') do |spec|
  spec.license = 'MIT'
  spec.author  = 'Seiei Miyagi'
  spec.add_dependency 'mruby-io-console'
end

# mruby/build_config.rb
MRuby::Build.new do |conf|
  conf.gem File.expand_path('../hi', File.dirname(__FILE__))
  toolchain :gcc
end
```

I fixed it in 20d7a28.

Then I got error when I set `config.enable_test` in build_config.rb like following:

```rb
MRuby::Build.new do |conf|
  conf.gem File.expand_path('../hi', File.dirname(__FILE__))
  toolchain :gcc
  # When there is conf.enable_test, I've got error like this:
  #   /Users/sei/src/github.com/hanachin/build_error_example_for_mruby-io-console/mruby/build/mrbgems/mruby-io-console/src/io-console.c:7:10: fatal error: 'mruby/ext/io.h'
  #         file not found
  #   #include "mruby/ext/io.h"
  #            ^
  #   1 error generated.
  conf.enable_test
end
```

I fixed it in 35659ac.

**Comment by ksss** [comment]
@hanachin Great and Thank you for reporting.
I'll check it later.

**Comment by ksss** [comment]
I could reproduce a build error!
And I also could confirm fix it with this PR.

Thank you ✨

**Comment by hanachin** [comment]
My pleasure 😄✨

**Pull request merged**
